title: Hi this is Merin
author: Merin Antony
email: 198586@ust-global.com
description: > # this means to ignore newlines until "baseurl:" Welcome! This is my webpage

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Merin-Antony-UST # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
